version: 2 

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per date with an orders_id and product_id
        tests: 
           - unique:
              column_name: "orders_id || pdt_id"
        columns:
         - name: date_date
         - name: orders_id
           tests:
           - not_null
         - name: pdt_id
           tests:
           - not_null
         - name: revenue
         - name: quantity
      - name: ship
        identifier: raw_gz_ship
        description: shipping details of Greenweez / one row per orders_id with corresponding data
        columns:
         - name: orders_id
           tests: 
           - unique 
           - not_null
         - name: shipping_fee
         - name: logcost
         - name: ship_cost

      - name: product
        identifier: raw_gz_product
        description: Product pricing at Greenweez / one row per product_id with corresponding price
        columns:
         - name: products_id
           tests: 
           - unique 
           - not_null
         - name: purchase_price

      - name: adwords
        identifier: raw_gz_adwords
        description: information on paid source - adwords and their corresponding campaigns / one row of campaign key and name per day
        columns:
         - name: date_date
         - name: paid_source		
         - name: campaign_key
         - name: camPGN_name
         - name: ads_cost
         - name: impression	
         - name: click

      - name: bing
        identifier: raw_gz_bing
        description: information on paid source - bing and their corresponding campaigns / one row of campaign key and name per day
        columns:
         - name: date_date
         - name: paid_source		
         - name: campaign_key
         - name: camPGN_name
         - name: ads_cost
         - name: impression	
         - name: click

      - name: criteo
        identifier: raw_gz_criteo
        description: information on paid source - criteo and their corresponding campaigns / one row of campaign key and name per day
        columns:
         - name: date_date
         - name: paid_source		
         - name: campaign_key
         - name: camPGN_name
         - name: ads_cost
         - name: impression	
         - name: click

      - name: facebook
        identifier: raw_gz_facebook
        description: information on paid source - facebook and their corresponding campaigns / one row of campaign key and name per day
        columns:
         - name: date_date
         - name: paid_source		
         - name: campaign_key
         - name: camPGN_name
         - name: ads_cost
         - name: impression	
         - name: click